SQL> 
SQL> DROP TABLE temp1;

Table dropped.

SQL> 
SQL> CREATE TABLE temp1 (
  2   restrictie VARCHAR2(30),
  3   tip_restrictie varchar(20),
  4   tabela VARCHAR2(30),
  5   expresie CLOB
  6   ) ;

Table created.

SQL> 
SQL> INSERT INTO temp1
  2   SELECT constraint_name, constraint_type, table_name,
  3    TO_LOB(search_condition)
  4   FROM user_constraints
  5   WHERE constraint_type = 'C' ;

77 rows created.

SQL> 
SQL> COMMIT ;

Commit complete.

SQL> 
SQL> SELECT 'ALTER TABLE ' || tabela || ' DROP CONSTRAINT ' || restrictie || ' ;'
  2   AS "--Stergere reguli de validare"
  3  FROM temp1
  4  WHERE expresie NOT LIKE '%NULL%' ;

--Stergere reguli de validare                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
-------------------------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
ALTER TABLE CONCEDII DROP CONSTRAINT CK_CONCEDII1 ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
ALTER TABLE CONCEDII DROP CONSTRAINT CK_CONCEDII2 ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
ALTER TABLE PERSONAL DROP CONSTRAINT CK_PERSONAL_MARCA ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
ALTER TABLE PERSONAL DROP CONSTRAINT CK_PERSONAL_NUMEPREN ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
ALTER TABLE PERSONAL DROP CONSTRAINT CK_PERSONAL_COMPART ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
ALTER TABLE PERSONAL DROP CONSTRAINT CK_PERSONAL_COLABORATOR ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ALTER TABLE RETINERI DROP CONSTRAINT CK_RETINERI_AN ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
ALTER TABLE RETINERI DROP CONSTRAINT CK_RETINERI_LUNA ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ALTER TABLE SALARII DROP CONSTRAINT CK_SALARII_AN ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
ALTER TABLE SALARII DROP CONSTRAINT CK_SALARII_LUNA ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
ALTER TABLE SPORURI DROP CONSTRAINT CK_SPORURI_AN ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
ALTER TABLE SPORURI DROP CONSTRAINT CK_SPORURI_LUNA ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
ALTER TABLE STUDENTI DROP CONSTRAINT CK_STUDENTI_PROFIL_DUR ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
ALTER TABLE STUDENTI DROP CONSTRAINT CK_STUDENTI_AN ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
ALTER TABLE STUDENTI DROP CONSTRAINT CK_STUDENTI_GRUPA ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

15 rows selected.

SQL> 
SQL> SELECT ' ALTER TABLE ' || tabela  || ' ADD CONSTRAINT ' || restrictie ||
  2   ' CHECK (' || CAST (expresie AS VARCHAR2(300)) || ') ;' AS "-- check-uri"
  3  FROM temp1
  4  WHERE expresie NOT LIKE '%NULL%' ;

-- check-uri                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 ALTER TABLE CONCEDII ADD CONSTRAINT CK_CONCEDII1 CHECK (dataf >= datai) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 ALTER TABLE CONCEDII ADD CONSTRAINT CK_CONCEDII2 CHECK (dataf - datai < 90) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 ALTER TABLE PERSONAL ADD CONSTRAINT CK_PERSONAL_MARCA CHECK ( marca > 0 ) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
 ALTER TABLE PERSONAL ADD CONSTRAINT CK_PERSONAL_NUMEPREN CHECK (numepren=LTRIM(INITCAP(numepren))) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
 ALTER TABLE PERSONAL ADD CONSTRAINT CK_PERSONAL_COMPART CHECK (compart in ( 'CONTA', 'FIN', 'PERS', 'MARK','PROD', 'IT' ) ) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 ALTER TABLE PERSONAL ADD CONSTRAINT CK_PERSONAL_COLABORATOR CHECK (colaborator IN ('D','N')) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 ALTER TABLE RETINERI ADD CONSTRAINT CK_RETINERI_AN CHECK ( an BETWEEN 2001 AND 2012 ) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 ALTER TABLE RETINERI ADD CONSTRAINT CK_RETINERI_LUNA CHECK (luna BETWEEN 1 AND 12) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
 ALTER TABLE SALARII ADD CONSTRAINT CK_SALARII_AN CHECK ( an BETWEEN 2001 AND 2012 ) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
 ALTER TABLE SALARII ADD CONSTRAINT CK_SALARII_LUNA CHECK (luna BETWEEN 1 AND 12) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 ALTER TABLE SPORURI ADD CONSTRAINT CK_SPORURI_AN CHECK ( an BETWEEN 2001 AND 2012 ) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
 ALTER TABLE SPORURI ADD CONSTRAINT CK_SPORURI_LUNA CHECK (luna BETWEEN 1 AND 12) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 ALTER TABLE STUDENTI ADD CONSTRAINT CK_STUDENTI_PROFIL_DUR CHECK (profil_dur IN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    ('EL', 'ES', 'AL', 'AS')) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 ALTER TABLE STUDENTI ADD CONSTRAINT CK_STUDENTI_AN CHECK (an BETWEEN 1 AND 5) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 ALTER TABLE STUDENTI ADD CONSTRAINT CK_STUDENTI_GRUPA CHECK (grupa BETWEEN 1 AND 10) ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

15 rows selected.

SQL> 
SQL> spool off
