-- Generated by Oracle SQL Developer Data Modeler 4.1.1.888
--   at:        2015-11-18 07:50:11 EET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

-- and fixed by MF


DROP
  TABLE cancelled_invoices CASCADE CONSTRAINTS ;

DROP
  TABLE counties CASCADE CONSTRAINTS ;

DROP
  TABLE current_contacts CASCADE CONSTRAINTS ;

DROP
  TABLE customer_monthly_stats CASCADE CONSTRAINTS ;

DROP
  TABLE customers CASCADE CONSTRAINTS ;

DROP
  TABLE former_contacts CASCADE CONSTRAINTS ;

DROP
  TABLE former_vat_percents CASCADE CONSTRAINTS ;

DROP
  TABLE invoice_details CASCADE CONSTRAINTS ;

DROP
  TABLE invoices CASCADE CONSTRAINTS ;

DROP
  TABLE months CASCADE CONSTRAINTS ;

DROP
  TABLE people CASCADE CONSTRAINTS ;

DROP
  TABLE postal_codes CASCADE CONSTRAINTS ;

DROP
  TABLE product_monthly_stats CASCADE CONSTRAINTS ;

DROP
  TABLE products CASCADE CONSTRAINTS ;

DROP
  TABLE receipt_details CASCADE CONSTRAINTS ;

DROP
  TABLE receipts CASCADE CONSTRAINTS ;

DROP
  TABLE refusals CASCADE CONSTRAINTS ;

DROP
  TABLE refused_products CASCADE CONSTRAINTS ;



CREATE
  TABLE cancelled_invoices
  (
    cancellation_dt TIMESTAMP WITH LOCAL TIME ZONE NOT NULL ,
    comments NVARCHAR2 (100) NULL ,
    invoice_id INTEGER NOT NULL
  )
 ;
ALTER TABLE cancelled_invoices ADD CONSTRAINT cancelled_invoices_PK PRIMARY KEY
( invoice_id ) NOT DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE counties
  (
    county_code CHAR (2) NOT NULL ,
    county_name NVARCHAR2 (50) NOT NULL ,
    county_region NVARCHAR2 (30) DEFAULT 'Moldova' NOT NULL
  )
 ;
ALTER TABLE counties ADD CONSTRAINT counties_PK PRIMARY KEY ( county_code ) NOT
DEFERRABLE ENABLE VALIDATE ;
ALTER TABLE counties ADD CONSTRAINT counties_county_name_UN UNIQUE (
county_name ) NOT DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE current_contacts
  (
    cust_id INTEGER NOT NULL ,
    position NVARCHAR2 (50) NOT NULL ,
    start_date DATE NOT NULL ,
    pers_id    INTEGER NOT NULL
  )
 ;
ALTER TABLE current_contacts ADD CONSTRAINT current_contacts_PK PRIMARY KEY (
cust_id, position, pers_id ) NOT DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE customer_monthly_stats
  (
    cust_id       INTEGER NOT NULL ,
    YEAR          NUMBER (4) NOT NULL ,
    MONTH         NUMBER (2) NOT NULL ,
    sales         NUMBER (14,2) NOT NULL ,
    refusals      NUMBER (14,2) NOT NULL ,
    cancellations NUMBER (14,2) NOT NULL ,
    received      NUMBER (14,2) NOT NULL
  )
 ;
ALTER TABLE customer_monthly_stats ADD CONSTRAINT cust_mon_stats_PK
PRIMARY KEY ( cust_id, YEAR, MONTH ) NOT DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE customers
  (
    cust_id INTEGER NOT NULL ,
    cust_name NVARCHAR2 (50) NOT NULL ,
    fiscal_code VARCHAR2 (20) NOT NULL ,
    cust_address NVARCHAR2 (100) NULL ,
    post_code CHAR(6)    NOT NULL ,
    cust_phone      CHAR (10) NULL ,
    cust_email      VARCHAR2 (70) NULL ,
    current_balance NUMBER (12,2) NOT NULL
  )
  ;
ALTER TABLE customers ADD CONSTRAINT customers_PK PRIMARY KEY ( cust_id ) NOT
DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE former_contacts
  (
    from_ DATE NOT NULL ,
    to_   DATE NOT NULL ,
    position NVARCHAR2 (50) NOT NULL ,
    comments NVARCHAR2 (100) NULL ,
    pers_id INTEGER NOT NULL ,
    cust_id INTEGER NOT NULL
  )
   ;
ALTER TABLE former_contacts ADD CONSTRAINT former_contacts_PK PRIMARY KEY (
pers_id, cust_id, from_ ) NOT DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE former_vat_percents
  (
    date_start  DATE NOT NULL ,
    date_until  DATE NULL ,
    VAT_percent NUMBER (4,2) NOT NULL ,
    product_id  INTEGER NOT NULL
  )
   ;
ALTER TABLE former_vat_percents ADD CONSTRAINT former_vat_percents_PK PRIMARY
KEY ( product_id, date_start ) NOT DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE invoice_details
  (
    invoice_id INTEGER NOT NULL ,
    row_number SMALLINT NOT NULL ,
    quantity   NUMBER (10,3) NOT NULL ,
    unit_price NUMBER (8,2) NOT NULL ,
    product_id INTEGER NOT NULL ,
    row_VAT    NUMBER (12,2) NULL
  )
   ;
ALTER TABLE invoice_details ADD CONSTRAINT invoice_details_PK PRIMARY KEY (
invoice_id, row_number ) NOT DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE invoices
  (
    invoice_id     INTEGER NOT NULL ,
    invoice_number INTEGER NOT NULL ,
    invoice_date   DATE NOT NULL ,
    cust_id        INTEGER NOT NULL ,
    comments NVARCHAR2 (300) NULL ,
    invoice_VAT     NUMBER (12,2) NOT NULL ,
    invoice_amount  NUMBER (12,2) NOT NULL ,
    amount_received NUMBER (12,2) NOT NULL ,
    amount_refused  NUMBER (12,2) NOT NULL ,
    n_of_rows       INTEGER NOT NULL ,
    is_closed       CHAR(1) DEFAULT 'N' NOT NULL ,
    invoice_status NVARCHAR2 (50) NULL
  )
   ;
ALTER TABLE invoices ADD CONSTRAINT invoices_PK PRIMARY KEY ( invoice_id ) NOT
DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE months
  (
    YEAR                NUMBER (4) NOT NULL ,
    MONTH               NUMBER (2) NOT NULL ,
    sales_total         NUMBER (14,2) NOT NULL ,
    refusals_total      NUMBER (14,2) NOT NULL ,
    cancellations_total NUMBER (14,2) NOT NULL ,
    received_total      NUMBER (12,2) NOT NULL
  )
   ;
ALTER TABLE months ADD CONSTRAINT months_PK PRIMARY KEY ( YEAR, MONTH ) NOT
DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE people
  (
    pers_id            INTEGER NOT NULL ,
    pers_national_code CHAR (13) NOT NULL ,
    pers_family_name NVARCHAR2 (75) NOT NULL ,
    pers_first_name NVARCHAR2 (50) NOT NULL ,
    pers_address NVARCHAR2 (100) NULL ,
    pers_genre CHAR (1) DEFAULT 'B' NOT NULL ,
    post_code  CHAR (6)    NULL ,
    home_phone   CHAR (10) NULL ,
    office_phone CHAR (10) NULL , -- here we fix "phone"
    mobile_phone CHAR (10) NULL ,
    pers_email   VARCHAR2 (50) NULL ,
    office_email VARCHAR2 (75) NULL
  )
 ;
ALTER TABLE people ADD CONSTRAINT people_PK PRIMARY KEY ( pers_id ) NOT
DEFERRABLE ENABLE VALIDATE ;
ALTER TABLE people ADD CONSTRAINT people_pers_national_code_UN UNIQUE (
pers_national_code ) NOT DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE postal_codes
  (
    post_code CHAR (6) NOT NULL ,
    town NVARCHAR2 (75) NOT NULL ,
    county_code CHAR (2)    NOT NULL
  )
 ;
ALTER TABLE postal_codes ADD CONSTRAINT postal_codes_PK PRIMARY KEY ( post_code
) NOT DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE product_monthly_stats
  (
    sales         NUMBER (12,2) NOT NULL ,
    refusals      NUMBER (12,2) NOT NULL ,
    cancellations NUMBER (12,2) NOT NULL ,
    product_id    INTEGER NOT NULL ,
    YEAR          NUMBER (4) NOT NULL ,
    MONTH         NUMBER (2) NOT NULL
  )
;
ALTER TABLE product_monthly_stats ADD CONSTRAINT prod_mon_stats_PK PRIMARY
KEY ( product_id, YEAR, MONTH ) NOT DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE products
  (
    product_id INTEGER NOT NULL ,
    product_name NVARCHAR2 (75) NOT NULL ,
    measure_unit VARCHAR2 (25 CHAR) NULL ,
    group_ NVARCHAR2 (50) NULL ,
    current_vat_percent NUMBER (4,2) NOT NULL
  )
	;
ALTER TABLE products ADD CONSTRAINT products_PK PRIMARY KEY ( product_id ) NOT
DEFERRABLE ENABLE VALIDATE ;


-- add a redundant/denormalized attribute in "receipt_details" - "receipt_date"
CREATE
  TABLE receipt_details
  (
    receipt_id INTEGER NOT NULL ,
    receipt_date         DATE NOT NULL ,
    invoice_id INTEGER NOT NULL ,
    amount     NUMBER (10,2) NOT NULL
  )
 ;
ALTER TABLE receipt_details ADD CONSTRAINT receipt_details_PK PRIMARY KEY (
invoice_id, receipt_id ) NOT DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE receipts
  (
    receipt_id           INTEGER NOT NULL ,
    receipt_date         DATE NOT NULL ,
    receipt_docum_type   VARCHAR2 (25) NULL ,
    receipt_docum_number VARCHAR2 (25) NULL ,
    receipt_docum_date   DATE NULL ,
    amount_paid          NUMBER (12,2) NOT NULL
  )
 ;
ALTER TABLE receipts ADD CONSTRAINT receipts_PK PRIMARY KEY ( receipt_id ) NOT
DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE refusals
  (
    refusal_id     INTEGER NOT NULL ,
    refusal_dt     TIMESTAMP WITH LOCAL TIME ZONE NULL ,
    refusal_amount NUMBER (12,2) NOT NULL ,
    invoice_id     INTEGER NOT NULL
  )
 ;
CREATE UNIQUE INDEX refusals__IDX ON refusals
  (
    invoice_id ASC
  )
  ;
ALTER TABLE refusals ADD CONSTRAINT refusals_PK PRIMARY KEY ( refusal_id ) NOT
DEFERRABLE ENABLE VALIDATE ;


CREATE
  TABLE refused_products
  (
    refused_quantity NUMBER (10,3) NOT NULL ,
    refusal_reason NVARCHAR2 (100) NULL ,
    refused_unit_price NUMBER (9,2) NULL ,
    product_id         INTEGER NOT NULL ,
    refusal_id         INTEGER NOT NULL
  )
 ;
ALTER TABLE refused_products ADD CONSTRAINT refused_products_PK PRIMARY KEY (
product_id, refusal_id ) NOT DEFERRABLE ENABLE VALIDATE ;


ALTER TABLE cancelled_invoices ADD CONSTRAINT cancelled_invoices_invoices_FK
FOREIGN KEY ( invoice_id ) REFERENCES invoices ( invoice_id ) 
	ON DELETE CASCADE;

ALTER TABLE current_contacts ADD CONSTRAINT current_contacts_customers_FK
FOREIGN KEY ( cust_id ) REFERENCES customers ( cust_id ) ;

ALTER TABLE current_contacts ADD CONSTRAINT current_contacts_people_FK FOREIGN
KEY ( pers_id ) REFERENCES people ( pers_id ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE customer_monthly_stats ADD CONSTRAINT
cust_mon_stats_cust_FK FOREIGN KEY ( cust_id ) REFERENCES customers
( cust_id ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE customer_monthly_stats ADD CONSTRAINT
cust_mon_stats_mon_FK FOREIGN KEY ( YEAR, MONTH ) REFERENCES months (
YEAR, MONTH ) ;

ALTER TABLE customers ADD CONSTRAINT customers_postal_codes_FK FOREIGN KEY (
post_code ) REFERENCES postal_codes ( post_code ) ;

ALTER TABLE former_contacts ADD CONSTRAINT former_contacts_customers_FK FOREIGN
KEY ( cust_id ) REFERENCES customers ( cust_id ) ;

ALTER TABLE former_contacts ADD CONSTRAINT former_contacts_people_FK FOREIGN
KEY ( pers_id ) REFERENCES people ( pers_id ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE former_vat_percents ADD CONSTRAINT form_vat_perc_FK
FOREIGN KEY ( product_id ) REFERENCES products ( product_id ) ;

ALTER TABLE invoice_details ADD CONSTRAINT invoice_details_invoices_FK FOREIGN
KEY ( invoice_id ) REFERENCES invoices ( invoice_id ) ;

ALTER TABLE invoice_details ADD CONSTRAINT invoice_details_products_FK FOREIGN
KEY ( product_id ) REFERENCES products ( product_id ) ;

ALTER TABLE invoices ADD CONSTRAINT invoices_customers_FK FOREIGN KEY ( cust_id
) REFERENCES customers ( cust_id ) ;

ALTER TABLE people ADD CONSTRAINT people_postal_codes_FK FOREIGN KEY (
post_code ) REFERENCES postal_codes ( post_code ) ;

ALTER TABLE postal_codes ADD CONSTRAINT postal_codes_counties_FK FOREIGN KEY (
county_code ) REFERENCES counties ( county_code ) ;

ALTER TABLE product_monthly_stats ADD CONSTRAINT prod_mon_stats_months_FK
FOREIGN KEY ( YEAR, MONTH ) REFERENCES months ( YEAR, MONTH ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE product_monthly_stats ADD CONSTRAINT
prod_monthly_stats_pr_FK FOREIGN KEY ( product_id ) REFERENCES products
( product_id ) ;

ALTER TABLE receipt_details ADD CONSTRAINT receipt_details_invoices_FK FOREIGN
KEY ( invoice_id ) REFERENCES invoices ( invoice_id ) ;

ALTER TABLE receipt_details ADD CONSTRAINT receipt_details_receipts_FK FOREIGN
KEY ( receipt_id ) REFERENCES receipts ( receipt_id ) ;

ALTER TABLE refusals ADD CONSTRAINT refusals_invoices_FK FOREIGN KEY (
invoice_id ) REFERENCES invoices ( invoice_id ) ;

ALTER TABLE refused_products ADD CONSTRAINT refused_products_products_FK
FOREIGN KEY ( product_id ) REFERENCES products ( product_id ) ;

ALTER TABLE refused_products ADD CONSTRAINT refused_products_refusals_FK
FOREIGN KEY ( refusal_id ) REFERENCES refusals ( refusal_id ) ;
