
DROP TABLE COUNTRIES CASCADE CONSTRAINTS ;
DROP TABLE AUTHORS CASCADE CONSTRAINTS ;
DROP TABLE PUBLISHERS CASCADE CONSTRAINTS ;
DROP TABLE BOOKS CASCADE CONSTRAINTS ;
DROP TABLE SALES CASCADE CONSTRAINTS ;
DROP TABLE BOOKS_AUTHORS CASCADE CONSTRAINTS ;
DROP TABLE KEYWORDS CASCADE CONSTRAINTS ;
DROP TABLE BOOKS_KEYWORDS CASCADE CONSTRAINTS ;

  CREATE TABLE COUNTRIES (	
  	COUNTRY_CODE VARCHAR(10) PRIMARY KEY, 
	COUNTRY_NAME VARCHAR(255) UNIQUE, 
	REGION VARCHAR(255), 
	INCOME_GROUP VARCHAR(255)
   ) ;

CREATE TABLE AUTHORS( 
    AUTHOR_CODE VARCHAR (5) NOT NULL PRIMARY KEY, 
    AUTHOR_NAME VARCHAR(75) NOT NULL CHECK ( SUBSTR(AUTHOR_NAME,1,1) = UPPER(SUBSTR(AUTHOR_NAME,1,1))) , 
    BIRTH_DATE DATE NOT NULL, 
    COUNTRY_CODE VARCHAR(10) CONSTRAINT AUTH_COUNTRIES_REF REFERENCES COUNTRIES (COUNTRY_CODE) 
    ) ;
 
CREATE TABLE PUBLISHERS (
    PUBLISH_NAME VARCHAR (30) NOT NULL CHECK ( SUBSTR(PUBLISH_NAME,1,1) = UPPER(SUBSTR(PUBLISH_NAME,1,1))) PRIMARY KEY,
    ADDRESS VARCHAR (50) NOT NULL, 
    CITY VARCHAR (20) NOT NULL CHECK ( SUBSTR(CITY,1,1) = UPPER(SUBSTR(CITY,1,1))),
    PUBLISH_COUNTRY_CODE VARCHAR(10) CONSTRAINT PUBLISH_COUNTRIES_REF REFERENCES COUNTRIES (COUNTRY_CODE) 
	);

CREATE TABLE BOOKS (
    TITLE  VARCHAR (100) NOT NULL, 
    ISBN  VARCHAR (13) NOT NULL PRIMARY KEY,  
    PUBLISH_NAME VARCHAR (30) NOT NULL 
              CONSTRAINT BOOKS_PUBLISH_REF REFERENCES PUBLISHERS (PUBLISH_NAME),
    RELEASE_YEAR NUMBER (4) NOT NULL,
    N_OF_PAGES NUMBER (5, 0) NOT NULL,
    CURRENT_PRICE NUMBER (10, 2) NOT NULL   
	);
    
CREATE TABLE SALES (
    ISBN  VARCHAR (13) NOT NULL CONSTRAINT SALES_BOOKS_REF REFERENCES BOOKS (ISBN), 
    YEAR NUMBER (4) NOT NULL, 
    MONTH NUMBER (2) NOT NULL,
    SALES NUMBER (14, 2) DEFAULT 0 NOT NULL, 
    PRIMARY KEY (ISBN, YEAR, MONTH)
	);

CREATE TABLE BOOKS_AUTHORS (
     ISBN  VARCHAR(13) NOT NULL CONSTRAINT BOOK_AUTH_BOOKS_REF REFERENCES BOOKS (ISBN), 
     AUTHOR_ORDER NUMBER (2, 0) NOT NULL, 
     AUTHOR_CODE VARCHAR(5) NOT NULL CONSTRAINT BOOK_AUTH_AUTHS_REF REFERENCES AUTHORS (AUTHOR_CODE),
     PRIMARY KEY (ISBN, AUTHOR_ORDER)
	);

CREATE TABLE KEYWORDS (
    KEYWORD VARCHAR(50) NOT NULL PRIMARY KEY,
    INCLUDED_IN_KEYWORD VARCHAR(50) CONSTRAINT KEYW_KEYW_REF 
    	REFERENCES KEYWORDS (KEYWORD) 
	);
    
CREATE TABLE BOOKS_KEYWORDS (
    ISBN  VARCHAR (13) NOT NULL CONSTRAINT BOOK_KEY_BOOKS_fk REFERENCES BOOKS (ISBN), 
    KEYWORD VARCHAR (50) NOT NULL CONSTRAINT BOOK_KEY_KEYS_fk REFERENCES KEYWORDS (KEYWORD),
    PRIMARY KEY( ISBN, KEYWORD)
	);  



