
DROP TABLE TARI CASCADE CONSTRAINTS ;
DROP TABLE AUTORI CASCADE CONSTRAINTS ;
DROP TABLE EDITURI CASCADE CONSTRAINTS ;
DROP TABLE CARTI CASCADE CONSTRAINTS ;
DROP TABLE VANZARI CASCADE CONSTRAINTS ;
DROP TABLE CARTI_AUTORI CASCADE CONSTRAINTS ;
DROP TABLE CUVINTE_CHEIE CASCADE CONSTRAINTS ;
DROP TABLE CARTI_CUVINTE_CHEIE CASCADE CONSTRAINTS ;

  CREATE TABLE TARI (	
  	COD_TARA VARCHAR(10) PRIMARY KEY, 
	NUME_TARA VARCHAR(255) UNIQUE, 
	REGIUNE VARCHAR(255), 
	GRUP_VENIT VARCHAR(255)
   ) ;

CREATE TABLE AUTORI( 
    COD_AUTOR VARCHAR (5) NOT NULL PRIMARY KEY, 
    NUME_AUTOR VARCHAR(75) NOT NULL CHECK ( SUBSTR(NUME_AUTOR,1,1) = UPPER(SUBSTR(NUME_AUTOR,1,1))) , 
    DATA_NASTERE DATE NOT NULL, 
    COD_TARA VARCHAR(10) CONSTRAINT autori_tari_REF REFERENCES TARI (COD_TARA) 
    ) ;
 
CREATE TABLE EDITURI (
    NUME_EDITURA VARCHAR (30) NOT NULL CHECK ( SUBSTR(NUME_EDITURA,1,1) = UPPER(SUBSTR(NUME_EDITURA,1,1))) PRIMARY KEY,
    ADRESA VARCHAR (50) NOT NULL, 
    LOCALITATE VARCHAR (20) NOT NULL CHECK ( SUBSTR(LOCALITATE,1,1) = UPPER(SUBSTR(LOCALITATE,1,1))),
    COD_TARA_ED VARCHAR(10) CONSTRAINT EDIT_tari_REF REFERENCES TARI (COD_TARA) 
	);

CREATE TABLE CARTI (
    TITLU  VARCHAR (100) NOT NULL, 
    ISBN  VARCHAR (13) NOT NULL PRIMARY KEY,  
    NUME_EDITURA VARCHAR (30) NOT NULL 
              CONSTRAINT carti_edit_fk REFERENCES EDITURI (NUME_EDITURA),
    AN_APARITIE NUMBER (4) NOT NULL,
    NR_PAGINI NUMBER (5, 0) NOT NULL,
    PRET_CURENT NUMBER (10, 2) NOT NULL   
	);
    
CREATE TABLE VANZARI (
    ISBN  VARCHAR (13) NOT NULL CONSTRAINT vanz_carti_fk REFERENCES CARTI (ISBN), 
    AN NUMBER (4) NOT NULL, 
    LUNA NUMBER (2) NOT NULL,
    VANZARI NUMBER (14, 2) DEFAULT 0 NOT NULL, 
    PRIMARY KEY (ISBN, AN, LUNA)
	);

CREATE TABLE CARTI_AUTORI (
     ISBN  VARCHAR(13) NOT NULL CONSTRAINT ca_carti_fk REFERENCES CARTI (ISBN), 
     AUTOR_NR NUMBER (2, 0) NOT NULL, 
     COD_AUTOR VARCHAR(5) NOT NULL CONSTRAINT ca_aut_fk REFERENCES AUTORI (COD_AUTOR),
     PRIMARY KEY (ISBN, AUTOR_NR)
	);

CREATE TABLE CUVINTE_CHEIE (
    CUVANT_CHEIE VARCHAR(50) NOT NULL PRIMARY KEY,
    CUVANT_CHEIE_SUPERIOR VARCHAR(50) CONSTRAINT cc_cc_fk 
    	REFERENCES CUVINTE_CHEIE (CUVANT_CHEIE) 
	);
    
CREATE TABLE CARTI_CUVINTE_CHEIE (
    ISBN  VARCHAR (13) NOT NULL CONSTRAINT ccc_carti_fk REFERENCES CARTI (ISBN), 
    CUVANT_CHEIE VARCHAR (50) NOT NULL CONSTRAINT ccc_cc_fk REFERENCES CUVINTE_CHEIE (CUVANT_CHEIE),
    PRIMARY KEY( ISBN, CUVANT_CHEIE)
	);  



